/*
 * Project: Axela.Script
 *
 * Copyright (c) 2020,  Prof. Dr. Nikolaus Wulff
 * University of Applied Sciences, Muenster, Germany
 * Lab for computer sciences (Lab4Inf).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package de.lab4inf.axela.script.javacc;

import java.io.StringReader;

/**
 * JavaCC based AxelaParser for scripting. This Parser only compiles after the
 * missing classes are generated by JavaCC, either with the Eclipse JavaCC
 * plugin or the gradle build.
 * 
 * 
 * @author nwulff
 * @since 29.11.2020
 */
public class AxelaJavaccParser extends JavaccParser {
	public AxelaJavaccParser() {
		this("");
	}

	public AxelaJavaccParser(String s) {
		this(new StringReader(s));
	}

	public AxelaJavaccParser(java.io.Reader stream) {
		super(stream);
	}
}
